charset: utf-8
defaults:
-
  values:
    layout: "default"
exclude: [
  README.md,
  CNAME
]
destination: _httpdocs
highlighter: rouge
markdown: kramdown
owner-name: Michael Spellacy
owner-email: spell@spellacy.net
owner-image: https://www.gravatar.com/avatar/89e429d4a3effa9601cd19a851c0003e.jpg
permalink: /:title/
repo: https://github.com/michaelspellacy/shouldiuseanaccessibilityoverlay-com
sass:
  style: :compressed
